package iccarus

type TagName string
type TagHeaderName string

const (
	TagCurve                      TagName = "curv"
	TagDescription                TagName = "desc"
	TagDictionary                 TagName = "dict"
	TagGamutBoundaryDescription   TagName = "gbd"
	TagModularAB                  TagName = "mAB"
	TagModularBA                  TagName = "mBA"
	TagMeasurement                TagName = "meas"
	TagMultiFunctionTable1        TagName = "mft1"
	TagMultiFunctionTable2        TagName = "mft2"
	TagMultiLocalizedUnicode      TagName = "mluc"
	TagParametricCurve            TagName = "para"
	TagProfileSequenceDescription TagName = "pseq"
	TagProfileSequenceIdentifier  TagName = "psid"
	TagS15Fixed16ArrayType        TagName = "sf32"
	TagSignatureType              TagName = "sig"
	TagText                       TagName = "text"
	TagView                       TagName = "view"
	TagXYZ                        TagName = "XYZ"
	TagZXML                       TagName = "ZXML"
)

const (
	TagHeaderAToB0                         TagHeaderName = "A2B0"
	TagHeaderAToB1                         TagHeaderName = "A2B1"
	TagHeaderAToB2                         TagHeaderName = "A2B2"
	TagHeaderBToA0                         TagHeaderName = "B2A0"
	TagHeaderBToA1                         TagHeaderName = "B2A1"
	TagHeaderBToA2                         TagHeaderName = "B2A2"
	TagHeaderCIEDistanceMap                TagHeaderName = "CIED"
	TagHeaderCxFData                       TagHeaderName = "CxF"
	TagHeaderDeviceSettings                TagHeaderName = "DEVS"
	TagHeaderDeviceDescription             TagHeaderName = "DevD"
	TagHeaderInformation                   TagHeaderName = "Info"
	TagHeaderInfoLower                     TagHeaderName = "info"
	TagHeaderBlueTRC                       TagHeaderName = "bTRC"
	TagHeaderBlueMatrixColumn              TagHeaderName = "bXYZ"
	TagHeaderMediaWhitePoint               TagHeaderName = "bkpt"
	TagHeaderChromaticAdaptationMatrix     TagHeaderName = "chad"
	TagHeaderColorimetricIntentImageState  TagHeaderName = "ciis"
	TagHeaderCopyright                     TagHeaderName = "cprt"
	TagHeaderDescription                   TagHeaderName = "desc"
	TagHeaderDeviceModelDescription        TagHeaderName = "dmdd"
	TagHeaderGreenTRC                      TagHeaderName = "gTRC"
	TagHeaderGreenMatrixColumn             TagHeaderName = "gXYZ"
	TagHeaderGamut                         TagHeaderName = "gamt"
	TagHeaderGamutBoundaryDesc0            TagHeaderName = "gbd0"
	TagHeaderGamutBoundaryDesc1            TagHeaderName = "gbd1"
	TagHeaderGamutBoundaryDesc2            TagHeaderName = "gbd2"
	TagHeaderGamutBoundaryDesc3            TagHeaderName = "gbd3"
	TagHeaderHDRStaticMetadata             TagHeaderName = "hd10"
	TagHeaderKTRC                          TagHeaderName = "kTRC"
	TagHeaderLuminance                     TagHeaderName = "lumi"
	TagHeaderMeasurement                   TagHeaderName = "meas"
	TagHeaderMetadata                      TagHeaderName = "meta"
	TagHeaderProfileSequenceDescription    TagHeaderName = "pseq"
	TagHeaderProfileSequenceIdentifier     TagHeaderName = "psid"
	TagHeaderRedTRC                        TagHeaderName = "rTRC"
	TagHeaderRedMatrixColumn               TagHeaderName = "rXYZ"
	TagHeaderRig0                          TagHeaderName = "rig0"
	TagHeaderTarget                        TagHeaderName = "targ"
	TagHeaderTechnology                    TagHeaderName = "tech"
	TagHeaderViewingConditions             TagHeaderName = "view"
	TagHeaderViewingEnvironmentDescription TagHeaderName = "vued"
	TagHeaderMediaWhitePointTag            TagHeaderName = "wtpt"
)
